version: '3'

services:
  heatmap:
    image: registry.gitlab.com/rumpel_freecodecamp/dataviz_d3_heatmap:latest
    build: .
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: "0.10"
          memory: 50M
    restart: always
    ports:
      - "8080:80"
    environment:
      - BASEPATH=
